//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorInfoClinicalTrial
    {
        public int Id { get; set; }
        public int SysClinicalTrialId { get; set; }
        public int SysDoctorInfoId { get; set; }
        public int MatchNotice { get; set; }
        public int AuditNotice { get; set; }
        public int IsMainAccount { get; set; }
    
        public virtual SysClinicalTrial SysClinicalTrial { get; set; }
        public virtual SysDoctorInfo SysDoctorInfo { get; set; }
    }
}
