//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HaoEntities : DbContext
    {
        public HaoEntities()
            : base("name=HaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<DoctorInfoClinicalTrial> DoctorInfoClinicalTrial { get; set; }
        public virtual DbSet<MatchQuestion> MatchQuestion { get; set; }
        public virtual DbSet<MatchRecord> MatchRecord { get; set; }
        public virtual DbSet<MatchRemarks> MatchRemarks { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientFile> PatientFile { get; set; }
        public virtual DbSet<SysClinicalGroup> SysClinicalGroup { get; set; }
        public virtual DbSet<SysClinicalSimple> SysClinicalSimple { get; set; }
        public virtual DbSet<SysClinicalTrial> SysClinicalTrial { get; set; }
        public virtual DbSet<SysDictionary> SysDictionary { get; set; }
        public virtual DbSet<SysDisease> SysDisease { get; set; }
        public virtual DbSet<SysDoctorInfo> SysDoctorInfo { get; set; }
        public virtual DbSet<SysOption> SysOption { get; set; }
        public virtual DbSet<SysQuestion> SysQuestion { get; set; }
        public virtual DbSet<SysRelated> SysRelated { get; set; }
        public virtual DbSet<SysUser> SysUser { get; set; }
    }
}
