//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientFile
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string Name { get; set; }
        public int FileType { get; set; }
        public string Path { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatorUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
