//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysClinicalSimple
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int SysClinicalTrialId { get; set; }
        public int SysQuestionId { get; set; }
        public int SortNumber { get; set; }
        public string MultipleAnswer { get; set; }
        public int SingleAnswer { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual SysClinicalTrial SysClinicalTrial { get; set; }
        public virtual SysQuestion SysQuestion { get; set; }
    }
}
