//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysClinicalTrial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysClinicalTrial()
        {
            this.DoctorInfoClinicalTrial = new HashSet<DoctorInfoClinicalTrial>();
            this.News = new HashSet<News>();
            this.SysClinicalGroup = new HashSet<SysClinicalGroup>();
            this.SysClinicalSimple = new HashSet<SysClinicalSimple>();
            this.SysDictionary8 = new HashSet<SysDictionary>();
        }
    
        public int Id { get; set; }
        public string TestRegistNum { get; set; }
        public string TestName { get; set; }
        public string DrugName { get; set; }
        public int DrugTypeId { get; set; }
        public int TreatmentTypeId { get; set; }
        public int SubjectMinAge { get; set; }
        public int SubjectMaxAge { get; set; }
        public int RecruitStatueId { get; set; }
        public int RecruitNumDomestic { get; set; }
        public int RecruitNumForeign { get; set; }
        public int MedicationTimeId { get; set; }
        public int ExperimentalStagingId { get; set; }
        public int SponsorId { get; set; }
        public int RecruitmentAgencyId { get; set; }
        public int RecruitmentHospitalId { get; set; }
        public string Details { get; set; }
        public int MatchPeopleNum { get; set; }
        public bool IsRecommend { get; set; }
        public Nullable<int> MainDoctorInfoId { get; set; }
        public string RemoveGroupInfo { get; set; }
        public string EntryGroupInfo { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModifyTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorInfoClinicalTrial> DoctorInfoClinicalTrial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalGroup> SysClinicalGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalSimple> SysClinicalSimple { get; set; }
        public virtual SysDictionary SysDictionary { get; set; }
        public virtual SysDictionary SysDictionary1 { get; set; }
        public virtual SysDictionary SysDictionary2 { get; set; }
        public virtual SysDictionary SysDictionary3 { get; set; }
        public virtual SysDictionary SysDictionary4 { get; set; }
        public virtual SysDictionary SysDictionary5 { get; set; }
        public virtual SysDictionary SysDictionary6 { get; set; }
        public virtual SysDictionary SysDictionary7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysDictionary> SysDictionary8 { get; set; }
    }
}
