//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDoctorInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysDoctorInfo()
        {
            this.DoctorInfoClinicalTrial = new HashSet<DoctorInfoClinicalTrial>();
            this.SysDoctorInfo1 = new HashSet<SysDoctorInfo>();
        }
    
        public int Id { get; set; }
        public string DoctorName { get; set; }
        public string DoctorPosition { get; set; }
        public string Hospital { get; set; }
        public string HospitalAddress { get; set; }
        public string InitialPassword { get; set; }
        public string RegistrationCall { get; set; }
        public int IsSubAccount { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int TrialsNum { get; set; }
        public int IsProvideAssessment { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModifyTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorInfoClinicalTrial> DoctorInfoClinicalTrial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysDoctorInfo> SysDoctorInfo1 { get; set; }
        public virtual SysDoctorInfo SysDoctorInfo2 { get; set; }
    }
}
