//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDictionary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysDictionary()
        {
            this.SysClinicalTrial = new HashSet<SysClinicalTrial>();
            this.SysClinicalTrial1 = new HashSet<SysClinicalTrial>();
            this.SysClinicalTrial2 = new HashSet<SysClinicalTrial>();
            this.SysClinicalTrial3 = new HashSet<SysClinicalTrial>();
            this.SysClinicalTrial4 = new HashSet<SysClinicalTrial>();
            this.SysClinicalTrial5 = new HashSet<SysClinicalTrial>();
            this.SysClinicalTrial6 = new HashSet<SysClinicalTrial>();
            this.SysClinicalTrial7 = new HashSet<SysClinicalTrial>();
            this.SysQuestion = new HashSet<SysQuestion>();
            this.SysClinicalTrial8 = new HashSet<SysClinicalTrial>();
        }
    
        public int Id { get; set; }
        public int Sort { get; set; }
        public string Value { get; set; }
        public int Type { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModifyTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysQuestion> SysQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalTrial> SysClinicalTrial8 { get; set; }
    }
}
