//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysOption()
        {
            this.SysRelated = new HashSet<SysRelated>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public int SysQuestionId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual SysQuestion SysQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysRelated> SysRelated { get; set; }
    }
}
