//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hao.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysQuestion()
        {
            this.SysClinicalGroup = new HashSet<SysClinicalGroup>();
            this.SysClinicalSimple = new HashSet<SysClinicalSimple>();
            this.SysOption = new HashSet<SysOption>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public int QuestionTypeId { get; set; }
        public int AnswerTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalGroup> SysClinicalGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysClinicalSimple> SysClinicalSimple { get; set; }
        public virtual SysDictionary SysDictionary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysOption> SysOption { get; set; }
    }
}
